name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    name: Build plugin and archive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Amazon Corretto JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build --stacktrace

      - name: Archive plugin as artifact on GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ModernChatInjector plugin jar
          path: build/libs/**.jar
